//! JSON-RPC method bodies that take `&mut DaemonState`. Slice 10c-b
//! seeds this module with `start_session`; slice 10c-d will add the
//! other session-mutation methods (`send_input`, `kill_session`,
//! `read_session_output`) as the TUI's `tui/src/control/methods.rs`
//! relocates here function-by-function.
//!
//! ## Why pure functions
//!
//! Method bodies live as standalone functions (not impl methods on
//! `DaemonState`) for the same reason `crate::attach`'s handlers do:
//! they're unit-testable without instantiating the dispatcher, the
//! wire layer, or a real accept loop. The dispatcher in
//! `crate::control::dispatch` is the only wrapper that knows about
//! `Caller` / `Request` / `Response` shapes; everything below it
//! takes plain Rust values.
//!
//! ## Authorization disposition at 10c-b
//!
//! `start_session` is **Operator-callable only** at this slice. The
//! reasoning:
//!
//! - The TUI path that will use it (slice 10c-e's `A-n` / `A-s` rewire)
//!   talks to the daemon as an Operator.
//! - The MCP-agent path (`Caller::Session` reaching `start_session`)
//!   needs descendant-task-tree validation against a *live* task list,
//!   which `DaemonState` doesn't have yet (the manifest snapshot is
//!   read-only and stale; the `tasks` field arrives with 10c-d when
//!   `send_input` and friends relocate). Rather than admit Session
//!   callers without validation, return `Unauthorized` with a pointer
//!   to the slice that lights this up — same pattern slice-10b used
//!   to punt `session.attach`.
//!
//! This is intentionally tighter than necessary for 10c-b's working-set
//! check ("TUI behavior unchanged") and graduates with 10c-d.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use serde::Deserialize;
use serde_json::{json, Value};

use base64::Engine;

use crate::control::protocol::ErrorCode;
use crate::session::{DaemonExitStatus, PendingSession, SpawnParams};
use crate::state::DaemonState;

/// Standard-padded base64. Matches `control::stream`'s encoding so
/// `read_session_output` bytes decode the same way TUI-side as
/// streamed attach bytes.
const BASE64: base64::engine::GeneralPurpose =
    base64::engine::general_purpose::STANDARD;

/// Cap on the `text` field of `send_input`. The wire frame is
/// already capped at 4 MiB; this tighter cap on the actual input
/// is a sanity check against an agent sending pasted-in megabytes
/// straight at a PTY. 64 KiB covers any realistic single keystroke
/// + clipboard paste while leaving plenty of slack under the wire
/// cap.
/// Maximum per-frame payload accepted by the daemon's
/// `send_input` JSON-RPC path and the attach-stream Input
/// branch. Both surfaces reject (RPC: InvalidParams + error /
/// stream: log + skip + continue) any frame whose decoded
/// payload exceeds this cap.
///
/// Public so the TUI's `StreamWriter::write` can mirror it via
/// `tui::term_shim::MAX_INPUT_FRAME_BYTES` and chunk client-side
/// (slice 10c-e-3b-fix5). The `client_and_daemon_input_caps_agree`
/// unit test in `tui/src/term_shim.rs::tests` pins the
/// constants in lockstep; if this value moves, that test fails
/// at build time and points at the mirror.
pub const MAX_SEND_INPUT_BYTES: usize = 64 * 1024;

/// Return type for every method handler in this module. Mirrors the
/// shape `tui/src/control/methods.rs::MethodResult` uses today, so
/// the eventual 10c-d relocation is mechanical.
pub type MethodResult = Result<Value, (ErrorCode, String)>;

/// `start_session` request params.
///
/// ## Wire shape (slice 10c-e-3b)
///
/// Pre-10c-e-3b this struct carried `type: "claude-code"|"codex"|"bash"`
/// and the daemon reconstructed argv via a hardcoded
/// `shell_for_type` map. That dropped everything the TUI's local
/// `Session::new` adds — `--mcp-config`, Codex MCP overrides,
/// `--resume` tokens, the systemd-run memory cap wrapper. The
/// daemon-spawned child would have no MCP servers configured,
/// resume tokens wouldn't connect to seeded transcripts, and cap
/// kills wouldn't fire. That's a material divergence from the
/// "no operator-visible behavior change" Phase 1 acceptance
/// criterion.
///
/// Post-10c-e-3b the daemon doesn't interpret an engine name. The
/// caller (TUI's `ClientSession::new`) builds full `argv`, full
/// `env`, the working directory, and the optional memory-cap
/// wrapper using the SAME code path the local `Session::new` uses
/// (`crate::mcp_config::build_args(SpawnTarget::Daemon, ...)` +
/// `tui::session::wrap_with_systemd_run`). The daemon's job
/// becomes "exec this argv with this env in this cwd" — agent-
/// specific knowledge stays TUI-side where the config files live.
#[derive(Deserialize)]
struct StartSessionParams {
    /// Stable session uid, pre-generated by the TUI before the
    /// MCP config file is written. Slice 10c-e-3b-fix: the TUI is
    /// the source of truth for uid identity — without this the
    /// daemon would mint its own uid inside `start_session`, but
    /// the TUI's `~/.cm/mcp/<uid>/claude.json` was already
    /// written with the pre-generated uid (because the env-block
    /// bakes `CM_TUI_SESSION_ID` at config-write time). Every
    /// downstream lookup (A-w kill, manifest binding, agent self-
    /// identification) keys on the same uid; a daemon-minted
    /// alternative would break all of those silently.
    ///
    /// The daemon validates the uid format (sanity, not security
    /// — the uid is forgeable by any caller with daemon-socket
    /// access) and checks for collision against
    /// `state.sessions`.
    uid: String,
    /// Stable workspace id to look up in `DaemonState.workspaces`.
    /// Used for manifest binding only — `working_dir` carries the
    /// actual cwd for the spawned child.
    workspace_id: String,
    /// Human-readable label shown in the sidebar. No semantic use.
    label: String,
    /// Full argv to exec. `argv[0]` is the program; any wrappers
    /// (e.g. `systemd-run --user --scope -- claude ...` for a
    /// memory-capped session) are baked in by the caller.
    argv: Vec<String>,
    /// Working directory for the spawned child. Pre-resolved to an
    /// absolute path on the TUI side so the daemon doesn't reach
    /// for `worktree_path` from its manifest snapshot — the caller
    /// is the source of truth.
    working_dir: String,
    /// Process env for the spawned child. The caller (TUI) populates
    /// this via `mcp_config::build_env(SpawnTarget::Daemon, ...)`
    /// so the spawned MCP server (if any) routes its callbacks to
    /// the daemon socket. The daemon doesn't inject anything beyond
    /// what's here.
    #[serde(default)]
    env: std::collections::BTreeMap<String, String>,
    /// Initial PTY width (columns). Defaults to 80 — the
    /// `SpawnParams::new` baseline, used by non-TUI callers or
    /// older clients that don't yet send the field. The TUI's
    /// `rpc_start_session` always sends the live operator
    /// terminal size so the daemon-spawned PTY matches what the
    /// user is looking at (slice-10c-e-2 review-3 fix: prior to
    /// this the daemon always opened 80x24 and full-screen apps
    /// misrendered until the first reactive Resize frame).
    #[serde(default = "default_cols")]
    cols: u16,
    /// Initial PTY height (rows). Same backstory as `cols`.
    #[serde(default = "default_rows")]
    rows: u16,
    /// Auto-register fallback for workspaces created mid-session
    /// before slice 10e's `manifest.watch` ships. The daemon's
    /// workspace map is loaded once at startup from
    /// `~/.cm/tui-sessions.json`; any workspace the TUI creates via
    /// `A-n` after the daemon started won't be in that map. When the
    /// TUI passes this field alongside an unknown `workspace_id`, the
    /// daemon registers a minimal workspace entry on the fly and
    /// proceeds with the spawn. Once 10e lands the bidirectional
    /// manifest path, this field becomes redundant but stays
    /// backwards-compatible (the daemon will just ignore it if the
    /// workspace_id is already present).
    ///
    /// `None` preserves the prior "NotFound for unknown workspace_id"
    /// behavior so non-daemon-aware callers see no change.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    worktree_path: Option<String>,
    /// Soft cap byte count for the memory-cap wrapper (slice
    /// 10c-e-3b-fix2). When `Some`, the spawned child is assumed
    /// to be wrapped via `systemd-run --user --scope ...
    /// MemoryHigh=<this>` (the TUI builds the argv that way
    /// in `app.rs::try_spawn_via_daemon`). The daemon uses the
    /// presence of this field as the signal to populate
    /// `SpawnParams.kills_dir` so the End-frame cap-kill
    /// attribution path can scan for records past its baseline.
    ///
    /// The actual cgroup-OOM watcher that *writes* those records
    /// hasn't relocated to the daemon yet — that's slice
    /// 10d-memory-cap-relocation. Until then, no kill records
    /// land for daemon-spawned sessions, so the End-frame's
    /// `memory_cap_kill` will always be `false`. The plumbing is
    /// in place; the producer is the missing piece.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    memory_cap_bytes: Option<u64>,
    /// Predicted cgroup path for the spawned session's
    /// systemd-run scope (slice 10c-e-3b-fix2). The TUI computes
    /// this in `wrap_with_systemd_run` and passes it through; the
    /// daemon stores it on `DaemonSession.cgroup_path` and echoes
    /// it in the `start_session` response so the TUI's
    /// `Session.cgroup_path` mirrors the local-spawn shape.
    ///
    /// Daemon doesn't currently *do* anything with this beyond
    /// the echo + future-watcher hook — slice
    /// 10d-memory-cap-relocation will pick it up.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    cgroup_path: Option<String>,
}

fn default_cols() -> u16 {
    80
}
fn default_rows() -> u16 {
    24
}

/// Spawn a new daemon-owned session.
///
/// ## What this does at 10c-b
///
/// - Validates `type_` against the same `{"claude-code","codex","bash"}`
///   allowlist `tui/src/control/methods.rs::start_session` enforces.
/// - Resolves `workspace_id` against the daemon's read-only manifest
///   snapshot (`DaemonState.workspaces`). Returns `NotFound` if the
///   workspace isn't in the snapshot; returns `Conflict` if it lacks
///   a `worktree_path` (the TUI's equivalent error path).
/// - Allocates a fresh session uid via [`new_session_uid`] using the
///   same `ts-<nanos>-<counter>` format as
///   `tui/src/app.rs::new_session_uid`. Daemon-minted uids are
///   indistinguishable from TUI-minted ones on the wire.
/// - Calls [`DaemonSession::spawn`] with the resolved working
///   directory, an env that injects `CM_TUI_SESSION_ID`, and the
///   binary name for the engine.
/// - Inserts the live session into `state.sessions` keyed by uid.
/// - Returns `{"session_uid": "<new uid>"}`.
///
/// ## What this does NOT do at 10c-b
///
/// - **Memory caps**: `DaemonSession` doesn't carry a `memory_cap`
///   field yet; that's slice 10c-d alongside the cap watcher
///   relocation.
/// - **MCP arg injection**: `claude-code` and `codex` get plain
///   `claude` / `codex` invocations. The TUI's `mcp_config::build_args`
///   adds `--mcp-config` and other flags that wire the MCP socket;
///   relocating that helper to the daemon is a 10c-e prerequisite.
/// - **Pending prompt delivery**: see [`StartSessionParams::prompt`].
/// - **Manifest write**: the daemon doesn't write
///   `~/.cm/tui-sessions.json` until slice 10e flips ownership. The
///   spawned session lives daemon-only at this slice; TUI sidebar
///   only learns about it when 10e's `manifest.watch` broadcasts a
///   diff.
pub fn start_session(
    state_arc: &Arc<Mutex<DaemonState>>,
    params: &Value,
) -> MethodResult {
    let p: StartSessionParams = serde_json::from_value(params.clone())
        .map_err(|e| (ErrorCode::InvalidParams, format!("params: {}", e)))?;

    if p.argv.is_empty() {
        return Err((
            ErrorCode::InvalidParams,
            "argv must be non-empty (argv[0] is the program to exec)".into(),
        ));
    }

    // Uid sanity check (10c-e-3b-fix): the TUI is the source of
    // truth for uid identity. We sanity-check the format here so a
    // malformed uid fails fast rather than landing in the registry
    // as a corruption hazard. This is NOT a security boundary —
    // the daemon socket is local + 0600 and any caller could
    // forge a uid; the check is "did the producer match the
    // documented format" so a typo / off-by-one bug surfaces
    // loudly. Format: `ts-<hex>-<hex>` (see
    // `tui/src/app.rs::new_session_uid`).
    if !is_valid_session_uid(&p.uid) {
        return Err((
            ErrorCode::InvalidParams,
            format!(
                "uid must match TUI format ts-<hex>-<hex>, got '{}'",
                p.uid
            ),
        ));
    }

    // Lock just for workspace lookup (with optional auto-register),
    // then drop. We must NOT hold the state lock across
    // `DaemonSession::spawn` (slow — opens PTY, forks child) or
    // across the insert (which acquires the lock itself) — and
    // crucially, we mustn't hold it when the reaper-cleanup callback
    // we set below would try to lock.
    //
    // Auto-register branch (slice 10c-e-3): the daemon snapshots
    // workspaces once at startup; mid-session A-n workspaces won't
    // be present until slice 10e's `manifest.watch` ships. When the
    // caller passes `worktree_path` alongside an unknown
    // `workspace_id`, register a minimal workspace entry on the fly.
    // No-op for callers that don't send the field (preserves the
    // "NotFound on unknown id" behavior). Once 10e lands, this
    // becomes redundant but stays harmless.
    {
        let mut state = state_arc.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        if !state.workspaces.contains_key(&p.workspace_id) {
            match p.worktree_path.as_deref() {
                Some(path_str) => {
                    let path = PathBuf::from(path_str);
                    state.workspaces.insert(
                        p.workspace_id.clone(),
                        crate::manifest::ManifestWorkspace {
                            id: p.workspace_id.clone(),
                            worktree_path: Some(path),
                            ..Default::default()
                        },
                    );
                }
                None => {
                    return Err((
                        ErrorCode::NotFound,
                        format!(
                            "workspace '{}' not in daemon's manifest snapshot \
                             (pre-10e: pass worktree_path to auto-register)",
                            p.workspace_id
                        ),
                    ));
                }
            }
        }
    }

    // Use the TUI-supplied uid verbatim (10c-e-3b-fix). The TUI's
    // MCP config already references this uid; minting a new one
    // here would silently desync every downstream consumer.
    let session_uid = p.uid.clone();

    // Slice 10c-e-3b-fix6: the collision check moved to the
    // Phase 2 lock-held insert below. Pre-fix6 the check
    // happened here, then the lock was dropped, then spawn
    // happened, then unconditional insert — two concurrent
    // `start_session` calls with the same uid could both pass
    // the guard, both spawn, both insert (last writer wins,
    // first child orphans). Re-checking under the same lock
    // that does the insert closes the TOCTOU window; if the
    // race is lost, `PendingSession`'s Drop SIGKILLs the
    // child via pidfd and we return Conflict cleanly. Same
    // recovery shape as the fix4a unverified-cgroup arm.

    let working_dir = PathBuf::from(&p.working_dir);

    // Build SpawnParams from the caller-supplied argv directly.
    // `argv[0]` is the program; `argv[1..]` is the args. The TUI's
    // `ClientSession::new` builds these via the same code path
    // `Session::new` uses locally (`mcp_config::build_args` +
    // `wrap_with_systemd_run`), so element-wise parity holds.
    let program = p.argv[0].clone();
    let mut spawn_params = SpawnParams::new(&session_uid, &p.label, &program);
    spawn_params.args = p.argv[1..].to_vec();
    spawn_params.working_dir = Some(working_dir);
    spawn_params.cols = p.cols;
    spawn_params.rows = p.rows;
    // Adopt the caller's env wholesale. The TUI provides the
    // MCP-server routing pin (`CM_TUI_SOCKET=""` /
    // `CM_DAEMON_SOCKET=<abs path>` per slice 10c-e-3a's
    // SpawnTarget::Daemon) plus `CM_TUI_SESSION_ID` and any
    // workflow vars. Daemon does not modify.
    for (k, v) in p.env {
        spawn_params.env.insert(k, v);
    }
    // Always pin `CM_TUI_SESSION_ID` to the daemon-minted uid even
    // if the caller didn't (or sent a different value). This is
    // the correlation key for `~/.cm/memory_kills/<uid>.jsonl`,
    // and the daemon owns the uid identity for daemon-spawned
    // sessions.
    spawn_params
        .env
        .insert("CM_TUI_SESSION_ID".into(), session_uid.clone());

    // Memory-cap plumbing (slice 10c-e-3b-fix2). When the TUI
    // indicates a cap was applied (via `memory_cap_bytes`), the
    // daemon populates `kills_dir` so the reaper's baseline +
    // probe path runs (`session.rs`'s `LastExitProbe::snapshot`
    // scans this directory at End-frame time). The actual
    // cgroup-OOM watcher hasn't relocated yet — that's slice
    // 10d-memory-cap-relocation — so no kill records will land
    // for daemon sessions; `memory_cap_kill` stays `false` until
    // the relocation. The plumbing is in place; the producer
    // moves over next.
    if p.memory_cap_bytes.is_some() {
        spawn_params.kills_dir = crate::path::default_kills_dir();
    }

    // === Phase 1: spawn child, no reaper yet. ===
    //
    // Done outside the state lock — spawn_command forks + execs
    // which is slow, and we don't want to serialize other RPCs
    // against it. `PendingSession` owns the live child via its
    // Box<dyn Child> handle; if anything below fails, dropping
    // the PendingSession SIGKILLs + waitpid'd the child cleanly.
    let pending = PendingSession::spawn(spawn_params)
        .map_err(|e| (ErrorCode::Internal, format!("spawn: {}", e)))?;

    // Slice 10c-e-3b-fix4a: post-spawn cgroup verification.
    //
    // When the caller indicated a memory cap (via
    // `memory_cap_bytes` + `cgroup_path`), the spawned argv is a
    // `systemd-run --user --scope ...` wrapper. systemd-run
    // returns success as soon as the *binary* starts, but the
    // scope itself can still fail to materialize (unit-name
    // collision, transient systemd error, cgroup-v2 namespace
    // quirk). Verify the cgroup is actually active before
    // declaring start_session a success — without this, the
    // daemon would echo back the predicted cgroup_path and the
    // operator would believe the cap is in place while the
    // child runs uncapped. Silent violation of the memory-cap
    // acceptance criterion.
    //
    // Mirrors `tui/src/session.rs::wait_for_cgroup_active`
    // semantics so local + daemon paths agree on what counts as
    // a valid memory-capped spawn. Drop on `PendingSession`
    // SIGKILLs the child if we bail here.
    let verified_cgroup_path: Option<String> = match p.cgroup_path.as_deref() {
        Some(predicted) => {
            let path = PathBuf::from(predicted);
            if !crate::path::wait_for_cgroup_active(&path, std::time::Duration::from_millis(500)) {
                return Err((
                    ErrorCode::Internal,
                    format!(
                        "memory-cap scope did not materialize as active at {} within 500ms — \
                         systemd-run likely failed (unit-name collision, scope refusal, or \
                         stale lingering cgroup with no processes). Refusing to return a \
                         session over an unverified cap.",
                        predicted
                    ),
                ));
            }
            Some(predicted.to_string())
        }
        None => {
            // No cgroup_path requested = no cap requested. The
            // caller is responsible for matching `memory_cap_bytes`
            // + `cgroup_path` presence; a request with one but not
            // the other is a structural caller bug, not a daemon
            // concern.
            None
        }
    };

    // Reaper-cleanup callback: remove the session from the
    // registry when the child exits. Fix #1 from the slice-10c-c
    // review-2: a fast-exit child cannot strand a dead entry,
    // because the lock-held arm_reaper-and-insert sequence below
    // forces the reaper's `on_exit` to either (a) run after our
    // insert (callback blocks on the lock we hold), or (b) run
    // never until our insert is visible (reaper thread hasn't
    // been spawned yet at that point).
    let state_for_cleanup = Arc::clone(state_arc);
    let uid_for_cleanup = session_uid.clone();
    let on_exit: Box<dyn FnOnce(&DaemonExitStatus) + Send + 'static> =
        Box::new(move |_status: &DaemonExitStatus| {
            let mut s = state_for_cleanup
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner());
            s.sessions.remove(&uid_for_cleanup);
        });

    // === Phase 2: arm reaper + insert, atomic under the lock. ===
    //
    // The lock is acquired BEFORE arm_reaper (which spawns the
    // reaper thread) and held through the insert. Possible
    // schedules:
    //
    //   - Child still alive when arm_reaper returns: reaper's
    //     wait_for_child blocks; on_exit fires asynchronously
    //     after the child eventually exits and we've long since
    //     unlocked. Cleanup runs correctly.
    //
    //   - Child already exited (fast-exit, e.g. `/bin/false`):
    //     reaper's wait_for_child returns immediately, on_exit
    //     fires, tries to lock state — blocks because WE hold
    //     the lock. We finish insert, unlock. on_exit's lock
    //     acquires, finds the entry we just inserted, removes
    //     it. Clean.
    //
    // The critical property: arm_reaper must NOT be called
    // before the lock is held. (Calling it before would let the
    // reaper fire before insert.)
    let mut state = state_arc.lock().unwrap_or_else(|p| p.into_inner());

    // Slice 10c-e-3b-fix6: lock-held uid collision check.
    // We must re-check the registry under the SAME lock that
    // does the insert; the pre-spawn check is racy because two
    // concurrent calls with the same uid can both pass it
    // (window between lock-drop and lock-reacquire-for-insert).
    // If the race is lost, drop the `PendingSession` — its Drop
    // SIGKILLs the child via pidfd — and return Conflict
    // cleanly. The losing thread doesn't strand a child.
    if state.sessions.contains_key(&session_uid) {
        drop(state); // release before dropping `pending` (Drop is fast but explicit)
        // `pending` drops at end-of-scope; its Drop kills the
        // child cleanly via pidfd. Explicit drop here for
        // intent — the kill happens whether we name it or not,
        // but naming it makes the recovery shape obvious to
        // readers.
        drop(pending);
        return Err((
            ErrorCode::Conflict,
            format!(
                "uid '{}' already exists in daemon registry — refusing to clobber \
                 a live session (race with concurrent start_session for same uid)",
                session_uid
            ),
        ));
    }

    let session = pending
        .arm_reaper(Some(on_exit))
        .map_err(|e| (ErrorCode::Internal, format!("arm reaper: {}", e)))?;
    state.sessions.insert(session_uid.clone(), session);
    drop(state);

    // Echo VERIFIED cgroup_path back to the TUI (slice
    // 10c-e-3b-fix4a). The path comes from the
    // post-spawn verification arm above — if the scope didn't
    // materialize as active, we already returned Internal and
    // never reach this point. The TUI can therefore treat this
    // field as authoritative: present ⇒ cap is in place;
    // absent ⇒ no cap requested.
    let mut response = json!({ "session_uid": session_uid });
    if let Some(cg) = verified_cgroup_path {
        response["cgroup_path"] = Value::String(cg);
    }
    Ok(response)
}

/// Sanity-check for a TUI-supplied session uid. Slice 10c-e-3b-fix:
/// the daemon no longer mints its own uid; the TUI is the source of
/// truth (see `StartSessionParams::uid`). We validate here so a
/// malformed uid fails fast with `InvalidParams` rather than landing
/// in the registry as a corruption hazard. Pattern:
/// `ts-<hex>-<hex>` — what `tui/src/app.rs::new_session_uid`
/// produces. Not a security check (the daemon socket is local +
/// 0600 and any caller could forge a uid); a typo / off-by-one in
/// the TUI's generator would just surface as InvalidParams instead
/// of weird downstream desync.
fn is_valid_session_uid(uid: &str) -> bool {
    let rest = match uid.strip_prefix("ts-") {
        Some(r) => r,
        None => return false,
    };
    let mut parts = rest.split('-');
    let (a, b, extra) = (parts.next(), parts.next(), parts.next());
    if extra.is_some() {
        return false;
    }
    match (a, b) {
        (Some(a), Some(b))
            if !a.is_empty()
                && !b.is_empty()
                && a.chars().all(|c| c.is_ascii_hexdigit())
                && b.chars().all(|c| c.is_ascii_hexdigit()) =>
        {
            true
        }
        _ => false,
    }
}

// ============================================================
// send_input (slice 10c-d)
// ============================================================

/// `send_input` request params. Mirrors the shape
/// `tui/src/control/methods.rs::SendInputParams` uses today.
#[derive(Deserialize)]
struct SendInputParams {
    /// Target session uid in `DaemonState.sessions`.
    session_uid: String,
    /// Bytes to write to the session's PTY input. Capped at
    /// [`MAX_SEND_INPUT_BYTES`].
    text: String,
    /// Append `\n` after writing the text. Defaults to true
    /// (matching the TUI handler's default — most callers want
    /// the agent to receive the prompt as a submission).
    #[serde(default = "default_submit")]
    submit: bool,
}

fn default_submit() -> bool {
    true
}

/// Write `params.text` to the target session's PTY.
///
/// ## At this slice (10c-d)
///
/// Operator-callable only (matches `start_session`'s disposition
/// — Session-caller descendant-task-tree validation lands in
/// 10c-e). Caller-scope authorization is enforced at the
/// dispatcher arm; this body assumes the caller is authorized.
///
/// The TUI's equivalent calls `agent::submit_prompt` which knows
/// about engine-specific submission formatting (pending_clear,
/// pending_jsonl_files tracking). The daemon's version writes raw
/// bytes + optional `\n`. That gap is intentional for the slice's
/// working-set discipline: agent-aware submission stays TUI-side
/// until the agent module relocates (planned alongside
/// `resolve_authorized_session` in a later slice).
pub fn send_input(
    state_arc: &Arc<Mutex<DaemonState>>,
    params: &Value,
) -> MethodResult {
    let p: SendInputParams = serde_json::from_value(params.clone())
        .map_err(|e| (ErrorCode::InvalidParams, format!("send_input params: {}", e)))?;

    if p.text.len() > MAX_SEND_INPUT_BYTES {
        return Err((
            ErrorCode::InvalidParams,
            format!(
                "text field {} bytes exceeds cap of {} bytes",
                p.text.len(),
                MAX_SEND_INPUT_BYTES
            ),
        ));
    }
    if !p.submit {
        // Phase-1 parity with the TUI: only submit=true is
        // wired. A typing path (no Enter) would need different
        // semantics around buffering / pending_clear and isn't
        // needed by any current MCP caller.
        return Err((
            ErrorCode::InvalidParams,
            "submit=false is not yet supported (matches TUI parity)".into(),
        ));
    }

    // Build the write payload BEFORE the state lock — text +
    // optional newline is just byte ops, no contention.
    let mut payload = p.text.into_bytes();
    if p.submit {
        payload.push(b'\n');
    }

    // Slice 10c-e-3b-fix3 deadlock fix: clone the writer Arc out
    // of state and check liveness under the state lock, then
    // drop state and do the blocking PTY write under just the
    // per-writer mutex. Pre-fix3 the state lock was held across
    // `write_all` — a backpressured PTY would deadlock every
    // other daemon RPC.
    let writer_arc = {
        let mut state = state_arc.lock().unwrap_or_else(|p| p.into_inner());
        let session = state.sessions.get_mut(&p.session_uid).ok_or_else(|| {
            (
                ErrorCode::NotFound,
                format!("session '{}' not in daemon registry", p.session_uid),
            )
        })?;
        // Liveness gate: a session whose child has exited has a
        // dead PTY. Surface Conflict for TUI parity. `try_wait`
        // drains the reaper's mpsc channel (side-effectful on
        // `cached_exit`), so we keep `get_mut` here for that.
        if session.try_wait().is_some() {
            return Err((
                ErrorCode::Conflict,
                format!(
                    "session '{}' has exited; PTY no longer writable",
                    p.session_uid
                ),
            ));
        }
        Arc::clone(&session.writer)
    };
    // State lock is dropped — now safe to do the blocking write
    // under just the per-writer mutex.
    {
        let mut w = writer_arc.lock().unwrap_or_else(|p| p.into_inner());
        w.write_all(&payload).and_then(|_| w.flush()).map_err(|e| {
            (
                ErrorCode::Internal,
                format!("send_input write to PTY: {}", e),
            )
        })?;
    }

    Ok(json!({ "ok": true }))
}

// ============================================================
// kill_session (slice 10c-d)
// ============================================================

#[derive(Deserialize)]
struct KillSessionParams {
    session_uid: String,
}

/// Terminate a session by removing it from the registry. The
/// `Drop` impl on the moved-out `DaemonSession` sends `SIGKILL`
/// via pidfd (the PID-reuse-safe primitive from slice-10c-b);
/// the reaper thread observes the exit asynchronously and the
/// reaper-cleanup callback's `remove` becomes a no-op (we just
/// removed). No deadlock: the callback's lock acquire blocks
/// briefly on our held mutex, then runs after we unlock.
///
/// ## At this slice (10c-d)
///
/// Operator-callable only. Manifest-write + tombstone-recording
/// the TUI does today are deferred to slice 10e (daemon-side
/// manifest ownership flip); for now `kill_session` simply
/// removes from the in-memory registry, which is sufficient for
/// `session.attach` against a killed UID to return `NotFound`.
pub fn kill_session(
    state_arc: &Arc<Mutex<DaemonState>>,
    params: &Value,
) -> MethodResult {
    let p: KillSessionParams = serde_json::from_value(params.clone())
        .map_err(|e| (ErrorCode::InvalidParams, format!("kill_session params: {}", e)))?;

    let mut state = state_arc.lock().unwrap_or_else(|p| p.into_inner());
    let removed = state.sessions.remove(&p.session_uid);
    if removed.is_none() {
        return Err((
            ErrorCode::NotFound,
            format!("session '{}' not in daemon registry", p.session_uid),
        ));
    }
    // Drop on the moved-out `DaemonSession` runs at scope-end of
    // this match arm — SIGKILL via pidfd, reaper observes exit.
    // The reaper's on_exit callback will try to lock the state and
    // remove the (now-absent) uid; that's a harmless no-op.
    drop(removed);

    Ok(json!({ "ok": true }))
}

// ============================================================
// read_session_output (slice 10c-d)
// ============================================================
//
// This is a fanout-snapshot method — distinct from the Python MCP
// tool of the same name in `mcp_server/server.py`, which composes
// `resolve_authorized_session` + a Python file-read. The daemon's
// method is the "give me what's currently buffered" surface; the
// Python tool is the "give me parsed transcript messages from disk"
// surface. Both can coexist.
//
// Wire shape returns a base64-encoded byte buffer + cursor /
// eviction flag matching `crate::session::FanoutSnapshot`.

#[derive(Deserialize)]
struct ReadSessionOutputParams {
    session_uid: String,
    /// Caller's cursor from a previous call. `None` on the first
    /// call returns the full current ring.
    #[serde(default)]
    since_cursor: Option<u64>,
}

/// Return a snapshot of the session's PTY-output fanout. See
/// [`crate::session::PtyByteFanout::snapshot_since`] for the
/// cursor semantics.
///
/// ## At this slice (10c-d)
///
/// Operator-callable only. Session-caller descendant-task-tree
/// validation lands in 10c-e (same gate as send_input /
/// kill_session). The response shape matches `FanoutSnapshot`
/// (bytes are base64-encoded for transport).
pub fn read_session_output(
    state_arc: &Arc<Mutex<DaemonState>>,
    params: &Value,
) -> MethodResult {
    let p: ReadSessionOutputParams = serde_json::from_value(params.clone())
        .map_err(|e| {
            (
                ErrorCode::InvalidParams,
                format!("read_session_output params: {}", e),
            )
        })?;

    let state = state_arc.lock().unwrap_or_else(|p| p.into_inner());
    let session = state.sessions.get(&p.session_uid).ok_or_else(|| {
        (
            ErrorCode::NotFound,
            format!("session '{}' not in daemon registry", p.session_uid),
        )
    })?;
    let snap = session.fanout.snapshot_since(p.since_cursor);
    Ok(json!({
        "bytes": BASE64.encode(&snap.bytes),
        "start_offset": snap.start_offset,
        "cursor": snap.cursor,
        "evicted_since_cursor": snap.evicted_since_cursor,
        "closed": snap.closed,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::ManifestWorkspace;
    use tempfile::TempDir;

    /// Construct a `DaemonState` with one workspace whose
    /// `worktree_path` points at a usable temp directory, already
    /// wrapped in `Arc<Mutex<…>>` (the form `start_session` now
    /// requires — slice-10c-c review fix #2).
    fn state_with_workspace(ws_id: &str, dir: &TempDir) -> Arc<Mutex<DaemonState>> {
        let mut s = DaemonState::new();
        s.workspaces.insert(
            ws_id.into(),
            ManifestWorkspace {
                id: ws_id.into(),
                name: "test-ws".into(),
                is_closed: false,
                is_cloud: false,
                worktree_path: Some(dir.path().to_path_buf()),
                main_repo_path: None,
                repo_url: None,
                worker_vm: None,
                worker_zone: None,
                sessions: Vec::new(),
                tombstones: Vec::new(),
            },
        );
        Arc::new(Mutex::new(s))
    }

    /// Drain all registered sessions and kill them. Tests should
    /// call this in their cleanup path even though `Drop` would
    /// SIGKILL via pidfd anyway — explicit cleanup avoids the
    /// reaper-cleanup callback racing with the test's assertions
    /// (a `/bin/bash` that exits because its tty closed would have
    /// the cleanup callback try to remove from the registry,
    /// generating a spurious lock contention).
    fn kill_all_sessions(state: &Arc<Mutex<DaemonState>>) {
        let mut s = state.lock().unwrap();
        for (_, mut sess) in s.sessions.drain() {
            let _ = sess.kill();
        }
    }

    /// Counter for unique TUI-format uids in tests. Slice 10c-e-3b-fix:
    /// the daemon now requires a TUI-supplied uid, so tests must
    /// generate one. Each call returns a freshly-uniquified
    /// `ts-<nanos>-<counter>` string that satisfies
    /// `is_valid_session_uid`.
    fn fresh_test_uid() -> String {
        use std::sync::atomic::{AtomicU64, Ordering};
        use std::time::{SystemTime, UNIX_EPOCH};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        format!("ts-{:x}-{:x}", nanos, n)
    }

    /// Build a `start_session` request body for a bare `/bin/bash`
    /// spawn against the supplied working directory. Helper for
    /// the slice 10c-e-3b argv/env/cwd wire shape — saves repeating
    /// the JSON in every test. Mints a fresh TUI-format uid each
    /// call (slice 10c-e-3b-fix: caller is source of truth for uid).
    fn bash_params(workspace_id: &str, label: &str, dir: &std::path::Path) -> Value {
        json!({
            "uid": fresh_test_uid(),
            "workspace_id": workspace_id,
            "label": label,
            "argv": ["/bin/bash"],
            "working_dir": dir.display().to_string(),
        })
    }

    // --- Param validation -----------------------------------------------------

    #[test]
    fn invalid_params_shape_returns_invalid_params() {
        // Required-field validation: a missing required field
        // (workspace_id here) surfaces as a serde error wrapped in
        // our InvalidParams code so clients get a typed pointer
        // rather than an opaque Internal. Every other required
        // field is supplied so the assertion isolates workspace_id.
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({
            "uid": fresh_test_uid(),
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": "/tmp",
            // intentionally omitting workspace_id
        });
        let err = start_session(&state, &params).expect_err("missing workspace_id");
        assert_eq!(err.0, ErrorCode::InvalidParams);
        assert!(
            err.1.contains("workspace_id"),
            "error should name the missing field: {}",
            err.1
        );
    }

    #[test]
    fn empty_argv_returns_invalid_params() {
        // Slice 10c-e-3b: the daemon no longer maps session_type to
        // hardcoded argv; the caller's `argv` field is authoritative.
        // An empty argv is a structural error — there's nothing to
        // exec.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-empty-argv", &dir);
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-empty-argv",
            "label": "x",
            "argv": [],
            "working_dir": dir.path().display().to_string(),
        });
        let err = start_session(&state, &params).expect_err("empty argv");
        assert_eq!(err.0, ErrorCode::InvalidParams);
        assert!(
            err.1.contains("argv"),
            "error should name the empty field: {}",
            err.1
        );
    }

    // --- Workspace resolution -----------------------------------------------

    #[test]
    fn missing_workspace_returns_not_found() {
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-does-not-exist",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": "/tmp",
        });
        let err = start_session(&state, &params).expect_err("missing ws");
        assert_eq!(err.0, ErrorCode::NotFound);
        assert!(err.1.contains("ws-does-not-exist"));
    }

    #[test]
    fn unknown_workspace_with_worktree_path_auto_registers_and_spawns() {
        // Named acceptance for slice 10c-e-3's auto-register
        // bridge: the daemon snapshots workspaces once at startup,
        // so an A-n workspace created mid-session is unknown to it
        // until 10e's manifest.watch lands. When the TUI passes
        // `worktree_path` alongside an unknown `workspace_id`, the
        // daemon registers a minimal workspace entry on the fly and
        // proceeds with the spawn — preserving the smoke-test
        // workflow without needing 10e first.
        let dir = TempDir::new().unwrap();
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let workspace_id = "ws-fresh-from-a-n";
        let worktree_path = dir.path().display().to_string();

        // Pre-check: the workspace is NOT in the map.
        assert!(
            state.lock().unwrap().workspaces.get(workspace_id).is_none(),
            "workspace must not be pre-registered"
        );

        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": workspace_id,
            "label": "shell",
            "argv": ["/bin/bash"],
            "working_dir": worktree_path,
            "worktree_path": worktree_path,
        });
        let result = start_session(&state, &params).expect("auto-register + spawn");
        let uid = result["session_uid"].as_str().unwrap().to_string();

        // The spawn succeeded AND the workspace got registered as a
        // side effect.
        {
            let s = state.lock().unwrap();
            let ws = s
                .workspaces
                .get(workspace_id)
                .expect("workspace auto-registered");
            assert_eq!(ws.id, workspace_id);
            assert_eq!(
                ws.worktree_path.as_ref().map(|p| p.display().to_string()),
                Some(worktree_path)
            );
            assert!(s.sessions.contains_key(&uid));
        }

        kill_all_sessions(&state);
    }

    #[test]
    fn unknown_workspace_without_worktree_path_still_returns_not_found() {
        // The auto-register branch is gated on the caller sending
        // `worktree_path`. Without it, prior "NotFound for unknown
        // id" behavior holds — non-daemon-aware callers see no
        // change.
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-unknown",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": "/tmp",
            // intentionally no worktree_path
        });
        let err = start_session(&state, &params).expect_err("no auto-register");
        assert_eq!(err.0, ErrorCode::NotFound);
        assert!(
            err.1.contains("worktree_path"),
            "error should hint at the auto-register field: {}",
            err.1
        );
    }

    #[test]
    fn worktree_path_for_existing_workspace_is_ignored_not_clobbered() {
        // A pre-existing workspace must not have its worktree_path
        // overwritten by the auto-register fallback. The daemon's
        // logic checks `contains_key` first; a present entry
        // short-circuits.
        let dir = TempDir::new().unwrap();
        let other = TempDir::new().unwrap();
        let state = state_with_workspace("ws-existing", &dir);
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-existing",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
            // A different path — must be ignored.
            "worktree_path": other.path().display().to_string(),
        });
        let result = start_session(&state, &params).expect("spawn ok");
        let uid = result["session_uid"].as_str().unwrap().to_string();

        // The original path stays.
        {
            let s = state.lock().unwrap();
            let ws = s.workspaces.get("ws-existing").unwrap();
            assert_eq!(
                ws.worktree_path.as_ref().map(|p| p.display().to_string()),
                Some(dir.path().display().to_string()),
                "pre-existing workspace's worktree_path must not be clobbered \
                 by an auto-register hint"
            );
            assert!(s.sessions.contains_key(&uid));
        }

        kill_all_sessions(&state);
    }

    #[test]
    fn cloud_workspace_can_be_spawned_into_when_caller_supplies_working_dir() {
        // Slice 10c-e-3b: the daemon no longer inspects
        // `workspace.worktree_path` — the caller's `working_dir`
        // is the source of truth for the spawn cwd. Pre-3b this
        // case returned `Conflict` because the daemon needed
        // workspace.worktree_path to populate cwd; now the
        // workspace lookup is purely an existence check.
        //
        // A cloud workspace (worktree_path = None) is fine as long
        // as the caller passes a usable `working_dir`. (The TUI's
        // own cloud path won't route through here in practice —
        // gcloud SSH stays TUI-local — but the daemon shouldn't
        // refuse on workspace shape alone.)
        let dir = TempDir::new().unwrap();
        let state = {
            let mut s = DaemonState::new();
            s.workspaces.insert(
                "ws-cloud".into(),
                ManifestWorkspace {
                    id: "ws-cloud".into(),
                    name: "cloud-ws".into(),
                    is_closed: false,
                    is_cloud: true,
                    worktree_path: None,
                    main_repo_path: None,
                    repo_url: None,
                    worker_vm: None,
                    worker_zone: None,
                    sessions: Vec::new(),
                    tombstones: Vec::new(),
                },
            );
            Arc::new(Mutex::new(s))
        };
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-cloud",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
        });
        let result = start_session(&state, &params)
            .expect("spawn into cloud-shaped workspace must work when caller supplies working_dir");
        let uid = result["session_uid"].as_str().unwrap().to_string();
        assert!(state.lock().unwrap().sessions.contains_key(&uid));
        kill_all_sessions(&state);
    }

    // --- Happy path --------------------------------------------------------

    #[test]
    fn spawn_bash_session_inserts_into_registry_and_returns_uid() {
        // The named acceptance criterion: handler runs a real
        // `/bin/bash` against the workspace's worktree_path, the
        // session lands in `state.sessions`, and the returned uid
        // matches the registry key.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-1", &dir);
        let params = bash_params("ws-1", "shell", dir.path());
        let result = start_session(&state, &params).expect("spawn ok");
        let uid = result["session_uid"]
            .as_str()
            .expect("session_uid in response")
            .to_string();
        assert!(uid.starts_with("ts-"), "uid format must be ts-*: {}", uid);

        // Inserted under the same key.
        {
            let s = state.lock().unwrap();
            let session = s.sessions.get(&uid).expect("session registered");
            assert_eq!(session.uid, uid);
            assert_eq!(session.title, "shell");
        }

        kill_all_sessions(&state);
    }

    // ===== Slice 10c-e-3b-fix: TUI-supplied uid passthrough =====

    #[test]
    fn supplied_uid_is_used_verbatim_in_registry_and_response() {
        // Named acceptance: a TUI-supplied uid flows through
        // verbatim — `state.sessions` keys on it AND the response
        // echoes it. Pre-fix the daemon minted a fresh uid inside
        // start_session and the TUI's MCP config (with the
        // pre-generated uid baked in) was desynced from the
        // daemon registry.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-uid-passthrough", &dir);
        let supplied_uid = "ts-feedface-1";
        let params = json!({
            "uid": supplied_uid,
            "workspace_id": "ws-uid-passthrough",
            "label": "passthrough",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
        });
        let result = start_session(&state, &params).expect("spawn");
        let returned = result["session_uid"].as_str().expect("session_uid");
        assert_eq!(
            returned, supplied_uid,
            "daemon must echo the TUI-supplied uid"
        );

        {
            let s = state.lock().unwrap();
            let session = s
                .sessions
                .get(supplied_uid)
                .expect("registry must key on supplied uid");
            assert_eq!(session.uid, supplied_uid);
        }

        kill_all_sessions(&state);
    }

    #[test]
    fn duplicate_uid_returns_conflict_without_clobbering_live_session() {
        // Collision guard: starting a session with a uid already
        // in `state.sessions` returns Conflict. Without this guard
        // the duplicate-insert would replace the live session's
        // DaemonSession handle and leak its child PTY.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-uid-dup", &dir);
        let uid = "ts-feedface-2";

        let params = json!({
            "uid": uid,
            "workspace_id": "ws-uid-dup",
            "label": "first",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
        });
        let _ok = start_session(&state, &params).expect("first spawn");

        // Second spawn with the same uid — must fail.
        let dup_params = json!({
            "uid": uid,
            "workspace_id": "ws-uid-dup",
            "label": "duplicate",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
        });
        let err = start_session(&state, &dup_params).expect_err("duplicate uid");
        assert_eq!(err.0, ErrorCode::Conflict);
        assert!(
            err.1.contains(uid),
            "error should name the colliding uid: {}",
            err.1
        );

        // First session is still in the registry and still alive
        // (not clobbered).
        {
            let s = state.lock().unwrap();
            let session = s
                .sessions
                .get(uid)
                .expect("first session must still be in registry");
            assert_eq!(
                session.title, "first",
                "the live session's metadata must come from the first spawn, not the duplicate"
            );
        }

        kill_all_sessions(&state);
    }

    #[test]
    fn concurrent_start_session_with_same_uid_one_succeeds_other_returns_conflict() {
        // Slice 10c-e-3b-fix6 named acceptance: two concurrent
        // threads call `start_session` with the SAME uid against
        // the same Arc<Mutex<DaemonState>>. The pre-fix6
        // collision check happened outside the insert-lock, so
        // both could pass the guard, both spawn, both insert
        // (last writer wins, first child orphans). The fix moves
        // the check to the same lock-acquisition that does the
        // insert; losing thread drops its PendingSession (Drop
        // SIGKILLs the child via pidfd) and returns Conflict.
        //
        // We hammer the race by spinning up N threads that all
        // race for the same uid. Exactly one must succeed; all
        // others must return Conflict; the registry must contain
        // exactly one session (no orphan).
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-race-uid", &dir);
        let shared_uid = fresh_test_uid();
        let working_dir_str = dir.path().display().to_string();

        let n_threads = 8;
        let mut handles = Vec::with_capacity(n_threads);
        for i in 0..n_threads {
            let state_c = state.clone();
            let uid_c = shared_uid.clone();
            let wd_c = working_dir_str.clone();
            handles.push(std::thread::spawn(move || {
                let params = json!({
                    "uid": uid_c,
                    "workspace_id": "ws-race-uid",
                    "label": format!("race-{}", i),
                    "argv": ["/bin/bash"],
                    "working_dir": wd_c,
                });
                start_session(&state_c, &params)
            }));
        }

        // Collect outcomes.
        let mut ok_count = 0;
        let mut conflict_count = 0;
        for h in handles {
            match h.join().unwrap() {
                Ok(_) => ok_count += 1,
                Err((code, _msg)) if code == ErrorCode::Conflict => conflict_count += 1,
                Err(other) => panic!("unexpected error from racing start_session: {:?}", other),
            }
        }

        assert_eq!(
            ok_count, 1,
            "exactly one start_session should succeed; got {} successes (race fix broken: \
             collision check not under insert lock)",
            ok_count
        );
        assert_eq!(
            conflict_count,
            n_threads - 1,
            "all other start_sessions should return Conflict; got {}",
            conflict_count
        );

        // Registry holds exactly the one winning session — no
        // orphan from a losing thread's spawn.
        {
            let s = state.lock().unwrap();
            assert_eq!(
                s.sessions.len(),
                1,
                "exactly one session in registry; got {} — losing threads stranded their children",
                s.sessions.len()
            );
            assert!(s.sessions.contains_key(&shared_uid));
        }

        kill_all_sessions(&state);
    }

    #[test]
    fn malformed_uid_returns_invalid_params() {
        // Sanity-check on format: the daemon validates the uid
        // matches the TUI's `ts-<hex>-<hex>` pattern. A malformed
        // uid is InvalidParams, not Internal — clients get a typed
        // pointer to the problem.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-bad-uid", &dir);

        for bad in &[
            "",                    // empty
            "no-ts-prefix",        // missing ts- prefix
            "ts-",                 // no segments
            "ts-abc",              // one segment
            "ts-abc-def-ghi",      // three segments
            "ts-XYZ-123",          // non-hex
            "ts-abc-",             // empty second segment
        ] {
            let params = json!({
                "uid": bad,
                "workspace_id": "ws-bad-uid",
                "label": "x",
                "argv": ["/bin/bash"],
                "working_dir": dir.path().display().to_string(),
            });
            let err = start_session(&state, &params).expect_err(
                &format!("malformed uid {:?} must error", bad),
            );
            assert_eq!(
                err.0,
                ErrorCode::InvalidParams,
                "uid {:?} should produce InvalidParams, got {:?}",
                bad,
                err
            );
            assert!(
                err.1.contains("uid") || err.1.contains("ts-"),
                "error should name the uid field: {}",
                err.1
            );
        }
    }

    // ===== Slice 10c-e-3b-fix2: memory-cap plumbing =====

    #[test]
    fn memory_cap_bytes_signals_kills_dir_default() {
        // Wire-shape acceptance for slice 10c-e-3b-fix2's memory-
        // cap plumbing: when the TUI sends `memory_cap_bytes`,
        // the daemon's spawn picks up the default kill-log
        // directory. The cgroup-OOM watcher hasn't relocated
        // yet (slice 10d-memory-cap-relocation will do that), so
        // no kill records actually land — but the kills_dir
        // being populated is what makes the reaper baseline +
        // probe path runnable, which is the foundation the
        // watcher relocation builds on.
        //
        // We can't directly inspect the daemon's
        // `DaemonSession.last_exit.kills_dir` (it's behind the
        // pubness boundary), so this test pins the observable:
        // a spawn with `memory_cap_bytes: Some(...)` succeeds
        // and registers. The internal kills_dir wiring is
        // exercised by the existing reaper tests; here we just
        // confirm the wire field is accepted.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-memcap", &dir);
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-memcap",
            "label": "memcap-test",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
            "memory_cap_bytes": 64 * 1024 * 1024u64,
        });
        let result = start_session(&state, &params).expect("spawn with cap ok");
        let uid = result["session_uid"].as_str().unwrap().to_string();
        assert!(state.lock().unwrap().sessions.contains_key(&uid));
        kill_all_sessions(&state);
    }

    // NOTE (slice 10c-e-3b-fix4a): the pre-fix4a
    // `cgroup_path_round_trips_in_response` test asserted that
    // the daemon echoed the supplied cgroup_path verbatim
    // without verification. That contract was a silent
    // memory-cap-criterion violation — a partial systemd-run
    // failure would leave the child running uncapped while the
    // daemon claimed success. After fix4a the daemon ONLY
    // echoes the path after verifying via
    // `wait_for_cgroup_active`. Coverage now lives in:
    //   - `unverified_cgroup_path_returns_internal_error`
    //     (the failure path; doesn't need real systemd-run).
    //   - For the success path, integration testing requires a
    //     real systemd-run scope, which depends on environment
    //     and isn't portable across CI. Track in
    //     slice-10d-memory-cap-relocation alongside the watcher
    //     relocation E2E test.

    #[test]
    fn unverified_cgroup_path_returns_internal_error() {
        // Slice 10c-e-3b-fix4a named acceptance: when the
        // caller requests a memory cap (`cgroup_path` present)
        // but the predicted cgroup doesn't materialize (e.g.
        // `systemd-run` partially failed, or — in this test —
        // we just point at a path that won't ever have a
        // cgroup.procs entry), `start_session` MUST return an
        // error rather than echoing the unverified path. The
        // PendingSession's Drop SIGKILLs the spawned child so
        // we don't leak it.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-bad-cgroup", &dir);
        // A path that exists but is NOT a cgroup with active
        // procs — the tempdir's own root is sufficient. No
        // `cgroup.procs` file there.
        let bogus_cgroup = dir.path().display().to_string();
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-bad-cgroup",
            "label": "verify-fail",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
            "memory_cap_bytes": 64 * 1024 * 1024u64,
            "cgroup_path": bogus_cgroup.clone(),
        });
        // Start. The verification arm should time out (no
        // cgroup.procs) and return Internal.
        let err =
            start_session(&state, &params).expect_err("verification should fail");
        assert_eq!(err.0, ErrorCode::Internal, "expected Internal, got {:?}", err);
        assert!(
            err.1.contains("memory-cap scope did not materialize") || err.1.contains(&bogus_cgroup),
            "error should name the verification failure: {}",
            err.1
        );
        // Registry must NOT contain a stranded entry — the
        // PendingSession's Drop cleaned up the child.
        assert!(
            state.lock().unwrap().sessions.is_empty(),
            "verification failure must NOT leave a session in the registry"
        );
    }

    #[test]
    fn no_memory_cap_means_no_cgroup_path_in_response() {
        // Symmetric: a spawn without memory_cap fields should
        // produce a response WITHOUT a `cgroup_path` key (rather
        // than `cgroup_path: null` or an empty string). The
        // local-spawn path mirrors this — Session.cgroup_path =
        // None when memory_cap is None.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-nocap", &dir);
        let params = bash_params("ws-nocap", "no-cap", dir.path());
        let result = start_session(&state, &params).expect("spawn ok");
        assert!(
            result.get("cgroup_path").is_none(),
            "response should omit cgroup_path entirely when no memory cap, got: {}",
            result
        );
        kill_all_sessions(&state);
    }

    #[test]
    fn is_valid_session_uid_unit() {
        // Direct unit test on the validator. Documents the format
        // contract (`ts-<hex>-<hex>`).
        assert!(is_valid_session_uid("ts-abc-1"));
        assert!(is_valid_session_uid("ts-deadbeef-cafe"));
        assert!(is_valid_session_uid("ts-0-0"));

        assert!(!is_valid_session_uid(""));
        assert!(!is_valid_session_uid("ts-"));
        assert!(!is_valid_session_uid("ts-abc"));
        assert!(!is_valid_session_uid("ts-abc-def-ghi"));
        assert!(!is_valid_session_uid("xs-abc-1"));
        assert!(!is_valid_session_uid("ts-XYZ-1")); // non-hex
        assert!(!is_valid_session_uid("ts--1")); // empty first segment
        assert!(!is_valid_session_uid("ts-abc-")); // empty second segment
    }

    #[test]
    fn cm_tui_session_id_env_is_injected_for_child() {
        // The named contract from `spawn_agent_session`: the child's
        // env has `CM_TUI_SESSION_ID=<own uid>`. Daemon-side spawn
        // must do the same so kill-log correlation continues to
        // work the way DESIGN_MEMORY_CAP.md describes.
        //
        // We can't directly inspect `DaemonSession`'s injected env
        // (it's private state inside portable-pty), so test the
        // observable consequence: run `bash -c 'echo
        // $CM_TUI_SESSION_ID'` and confirm the uid comes back
        // through the fanout.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-env", &dir);
        let params = bash_params("ws-env", "env-test", dir.path());
        let result = start_session(&state, &params).expect("ok");
        let uid = result["session_uid"].as_str().unwrap().to_string();

        // Subscribe to the fanout and send input under the state lock.
        let rx = {
            let mut s = state.lock().unwrap();
            let session = s.sessions.get_mut(&uid).expect("registered");
            let rx = session.fanout.subscribe();
            session
                .send_input(b"echo CM_TUI_SESSION_ID=$CM_TUI_SESSION_ID\n")
                .expect("send_input");
            rx
        };

        // Drain bytes until we either see the uid or time out.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        let mut accumulated = Vec::new();
        while std::time::Instant::now() < deadline {
            let remaining =
                deadline.saturating_duration_since(std::time::Instant::now());
            match rx.recv_timeout(remaining) {
                Ok(chunk) => {
                    accumulated.extend_from_slice(&chunk);
                    let text = String::from_utf8_lossy(&accumulated);
                    if text.contains(&format!("CM_TUI_SESSION_ID={}", uid)) {
                        kill_all_sessions(&state);
                        return;
                    }
                }
                Err(_) => break,
            }
        }
        kill_all_sessions(&state);
        panic!(
            "expected CM_TUI_SESSION_ID={} in child output, got:\n{}",
            uid,
            String::from_utf8_lossy(&accumulated)
        );
    }

    #[test]
    fn two_consecutive_spawns_with_distinct_uids_both_land_in_registry() {
        // Slice 10c-e-3b-fix: uids are caller-supplied. The TUI's
        // generator (`tui/src/app.rs::new_session_uid`) mixes a
        // nanos timestamp with an atomic counter, so distinct
        // uids are the steady state. The daemon must accept both
        // without conflict and key the registry on each.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-two", &dir);
        // Two requests with intentionally distinct uids
        // (`bash_params` already mints a fresh uid per call via
        // `fresh_test_uid()`).
        let params1 = bash_params("ws-two", "x", dir.path());
        let params2 = bash_params("ws-two", "x", dir.path());
        let r1 = start_session(&state, &params1).expect("first");
        let r2 = start_session(&state, &params2).expect("second");
        let uid1 = r1["session_uid"].as_str().unwrap();
        let uid2 = r2["session_uid"].as_str().unwrap();
        assert_ne!(uid1, uid2, "two spawns must produce distinct uids");
        assert_eq!(state.lock().unwrap().sessions.len(), 2);
        kill_all_sessions(&state);
    }

    // --- Reaper-driven cleanup (slice-10c-c review fix #2) -----------------

    #[test]
    fn exited_session_is_removed_from_registry_within_bound() {
        // Headline acceptance for fix #2: after a session's child
        // exits, the reaper-installed callback removes the entry
        // from `state.sessions`. Verifiable by spawning a session
        // that exits quickly (use `bash -c 'exit 0'`) and polling
        // `state.sessions.contains_key(&uid)` until it returns
        // false, with a 3s bound.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-exit", &dir);

        // The argv shape is interactive `/bin/bash`. Send `exit\n`
        // via send_input to make the bash session terminate.
        let params = bash_params("ws-exit", "exit-test", dir.path());
        let result = start_session(&state, &params).expect("spawn");
        let uid = result["session_uid"].as_str().unwrap().to_string();
        {
            let mut s = state.lock().unwrap();
            let session = s.sessions.get_mut(&uid).expect("registered");
            session.send_input(b"exit\n").expect("send_input exit");
        }

        // Poll until the session is gone from the registry. The
        // reaper-cleanup callback re-locks state through the same
        // mutex; ms-scale latency is typical.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        loop {
            {
                let s = state.lock().unwrap();
                if !s.sessions.contains_key(&uid) {
                    return;
                }
            }
            if std::time::Instant::now() >= deadline {
                panic!(
                    "session {} still in registry 3s after child exited — \
                     reaper-cleanup callback didn't fire",
                    uid
                );
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
    }

    #[test]
    fn fast_exit_child_never_leaks_dead_registry_entry() {
        // Named regression from the slice-10c-c review #2 fix
        // (two-phase spawn). Before the fix, a child that exited
        // between `DaemonSession::spawn`'s return and the
        // `start_session` insert would have its on_exit callback
        // fire against an empty registry — the later insert then
        // stranded a dead entry forever.
        //
        // After the fix, `start_session` uses `PendingSession::spawn`
        // + lock-held `arm_reaper`-and-insert, so the on_exit
        // callback either (a) fires after our unlock (clean), or
        // (b) blocks on our lock until insert completes (clean).
        //
        // We exercise this with a custom workspace whose shell IS
        // a fast-exit binary. The standard claude-code/codex/bash
        // path doesn't admit `/bin/false`, so we test the race at
        // the layer below — via `PendingSession::spawn` +
        // `arm_reaper` directly with the same lock-held pattern
        // `start_session` uses. 50 iterations to amplify any
        // scheduling-dependent flakiness.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-fast", &dir);

        for i in 0..50 {
            let uid = format!("ts-fast-{}", i);

            // PendingSession::spawn against /bin/false — exits
            // immediately with code 1.
            let mut spawn_params =
                crate::session::SpawnParams::new(&uid, "fast-exit", "/bin/false");
            spawn_params.working_dir = Some(dir.path().to_path_buf());
            let pending = crate::session::PendingSession::spawn(spawn_params)
                .expect("phase 1 spawn ok");

            let state_for_cleanup = Arc::clone(&state);
            let uid_for_cleanup = uid.clone();
            let on_exit: Box<dyn FnOnce(&DaemonExitStatus) + Send + 'static> =
                Box::new(move |_status: &DaemonExitStatus| {
                    let mut s = state_for_cleanup
                        .lock()
                        .unwrap_or_else(|p| p.into_inner());
                    s.sessions.remove(&uid_for_cleanup);
                });

            // Lock-held arm + insert (the race-closing pattern).
            {
                let mut s = state.lock().unwrap();
                let session = pending
                    .arm_reaper(Some(on_exit))
                    .expect("phase 2 arm ok");
                s.sessions.insert(uid.clone(), session);
            }

            // Within a bounded window, the registry must either
            // (a) not contain uid (cleanup already ran), or
            // (b) contain a session whose try_wait reports it as
            //     still running. Anything else is a leaked dead
            //     entry — the very bug this slice fixes.
            let deadline =
                std::time::Instant::now() + std::time::Duration::from_secs(3);
            loop {
                let cleaned = {
                    let s = state.lock().unwrap();
                    !s.sessions.contains_key(&uid)
                };
                if cleaned {
                    break;
                }
                if std::time::Instant::now() >= deadline {
                    // Liveness check before failing: maybe the
                    // child is genuinely still alive? (Shouldn't
                    // be — /bin/false exits in µs — but be honest
                    // if it is.)
                    let alive = {
                        let mut s = state.lock().unwrap();
                        s.sessions
                            .get_mut(&uid)
                            .and_then(|sess| {
                                if sess.try_wait().is_some() {
                                    None
                                } else {
                                    Some(())
                                }
                            })
                            .is_some()
                    };
                    if alive {
                        panic!(
                            "iter {}: child still alive after 3s (unexpected for /bin/false)",
                            i
                        );
                    } else {
                        panic!(
                            "iter {}: child exited but session {} STILL in registry 3s later — fast-exit race regression",
                            i, uid
                        );
                    }
                }
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
        }

        // No leftover entries from any iteration.
        assert_eq!(
            state.lock().unwrap().sessions.len(),
            0,
            "registry must be empty after all 50 fast-exit iterations",
        );
    }

    #[test]
    fn registry_remove_races_safely_against_insert() {
        // Fix-2 race contract: even if the child exits very fast
        // (before `start_session` returns), the reaper-cleanup
        // callback's `state.lock()` serializes with the insert
        // via the Arc<Mutex<…>>. By the time the callback's
        // remove runs, the insert has completed → the session
        // briefly appears in the registry, then is removed.
        //
        // We approximate "very fast exit" by using `bash` and
        // exiting immediately. The race window is theoretical
        // (thread-spawn overhead vs. mutex lock latency) but we
        // assert the invariant either way: the registry never
        // ends up with a stranded entry.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-race", &dir);

        for _ in 0..5 {
            let params = bash_params("ws-race", "race-test", dir.path());
            let result = start_session(&state, &params).expect("spawn");
            let uid = result["session_uid"].as_str().unwrap().to_string();
            // Send `exit` immediately to drive a fast exit.
            {
                let mut s = state.lock().unwrap();
                if let Some(session) = s.sessions.get_mut(&uid) {
                    let _ = session.send_input(b"exit\n");
                }
            }
            // Wait for the registry to reflect the exit.
            let deadline =
                std::time::Instant::now() + std::time::Duration::from_secs(3);
            while std::time::Instant::now() < deadline {
                if !state.lock().unwrap().sessions.contains_key(&uid) {
                    break;
                }
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
            assert!(
                !state.lock().unwrap().sessions.contains_key(&uid),
                "iteration: session {} not cleaned up within 3s",
                uid
            );
        }
        // No leftover entries.
        assert_eq!(
            state.lock().unwrap().sessions.len(),
            0,
            "registry must be empty after all sessions exit + cleanup",
        );
    }

    // --- initial PTY size plumbing (slice-10c-e-2 review-3 fix) ----------

    #[test]
    fn start_session_default_cols_rows_used_when_not_provided() {
        // Backwards-compat: a request without cols/rows fields
        // gets the 80/24 default. The bash session's PTY ends up
        // at that size via SpawnParams. We verify by reading
        // `stty size` output through the fanout.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-defsize", &dir);
        // No cols/rows in params — serde defaults kick in.
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-defsize",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
        });
        let result = start_session(&state, &params).expect("spawn");
        let uid = result["session_uid"].as_str().unwrap().to_string();

        let rx = {
            let mut s = state.lock().unwrap();
            let session = s.sessions.get_mut(&uid).unwrap();
            let rx = session.fanout.subscribe();
            session.send_input(b"stty size\n").expect("send_input");
            rx
        };

        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        let mut accumulated = Vec::new();
        while std::time::Instant::now() < deadline {
            let remaining =
                deadline.saturating_duration_since(std::time::Instant::now());
            match rx.recv_timeout(remaining) {
                Ok(chunk) => {
                    accumulated.extend_from_slice(&chunk);
                    let text = String::from_utf8_lossy(&accumulated);
                    if text.contains("24 80") {
                        kill_all_sessions(&state);
                        return;
                    }
                }
                Err(_) => break,
            }
        }
        kill_all_sessions(&state);
        panic!(
            "default 80x24 PTY size not observable via stty (looking for '24 80'): {}",
            String::from_utf8_lossy(&accumulated)
        );
    }

    #[test]
    fn start_session_with_explicit_cols_rows_sizes_pty_accordingly() {
        // Named acceptance for the slice-10c-e-2 review-3 fix:
        // the TUI's live operator terminal size must reach the
        // daemon-spawned PTY. Verify by spawning with non-default
        // 120x40, sending `stty size`, and observing the output
        // is "40 120".
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-bigsize", &dir);
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": "ws-bigsize",
            "label": "x",
            "argv": ["/bin/bash"],
            "working_dir": dir.path().display().to_string(),
            "cols": 120u16,
            "rows": 40u16,
        });
        let result = start_session(&state, &params).expect("spawn");
        let uid = result["session_uid"].as_str().unwrap().to_string();

        let rx = {
            let mut s = state.lock().unwrap();
            let session = s.sessions.get_mut(&uid).unwrap();
            let rx = session.fanout.subscribe();
            session.send_input(b"stty size\n").expect("send_input");
            rx
        };

        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        let mut accumulated = Vec::new();
        while std::time::Instant::now() < deadline {
            let remaining =
                deadline.saturating_duration_since(std::time::Instant::now());
            match rx.recv_timeout(remaining) {
                Ok(chunk) => {
                    accumulated.extend_from_slice(&chunk);
                    let text = String::from_utf8_lossy(&accumulated);
                    if text.contains("40 120") {
                        kill_all_sessions(&state);
                        return;
                    }
                }
                Err(_) => break,
            }
        }
        kill_all_sessions(&state);
        panic!(
            "expected '40 120' from stty size, got:\n{}",
            String::from_utf8_lossy(&accumulated)
        );
    }

    // ===========================================================
    // send_input (slice 10c-d)
    // ===========================================================

    /// Helper: spawn a bash session via the registered start_session
    /// path so the registry, reaper-cleanup callback, and Drop
    /// machinery are all live. Returns the session uid. The working
    /// directory is read from the pre-registered workspace's
    /// `worktree_path` — callers stage that via
    /// `state_with_workspace`.
    fn spawn_bash(state: &Arc<Mutex<DaemonState>>, ws_id: &str) -> String {
        let working_dir = state
            .lock()
            .unwrap()
            .workspaces
            .get(ws_id)
            .and_then(|w| w.worktree_path.clone())
            .expect("workspace must have a worktree_path for the test")
            .display()
            .to_string();
        let params = json!({
            "uid": fresh_test_uid(),
            "workspace_id": ws_id,
            "label": "test-bash",
            "argv": ["/bin/bash"],
            "working_dir": working_dir,
        });
        let result = start_session(state, &params).expect("spawn bash");
        result["session_uid"].as_str().unwrap().to_string()
    }

    #[test]
    fn send_input_writes_text_to_pty_and_returns_ok() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-si", &dir);
        let uid = spawn_bash(&state, "ws-si");

        // Subscribe so we can observe what bash echoes back.
        let rx = {
            let mut s = state.lock().unwrap();
            s.sessions.get_mut(&uid).unwrap().fanout.subscribe()
        };

        let params = json!({
            "session_uid": &uid,
            "text": "echo hello-send-input-test",
        });
        let result = send_input(&state, &params).expect("send_input ok");
        assert_eq!(result["ok"], true);

        // Observable consequence: bash echoes the line back through
        // the PTY → fanout. Look for the substring within a bounded
        // window.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        let mut accumulated = Vec::new();
        while std::time::Instant::now() < deadline {
            let remaining =
                deadline.saturating_duration_since(std::time::Instant::now());
            match rx.recv_timeout(remaining) {
                Ok(chunk) => {
                    accumulated.extend_from_slice(&chunk);
                    if String::from_utf8_lossy(&accumulated)
                        .contains("hello-send-input-test")
                    {
                        kill_all_sessions(&state);
                        return;
                    }
                }
                Err(_) => break,
            }
        }
        kill_all_sessions(&state);
        panic!(
            "expected 'hello-send-input-test' in PTY output, got:\n{}",
            String::from_utf8_lossy(&accumulated)
        );
    }

    #[test]
    fn send_input_rejects_oversize_text() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-si-big", &dir);
        let uid = spawn_bash(&state, "ws-si-big");

        // 64 KiB + 1 — one byte past the cap.
        let text = "a".repeat(MAX_SEND_INPUT_BYTES + 1);
        let params = json!({ "session_uid": &uid, "text": text });
        let err = send_input(&state, &params).expect_err("oversize must reject");
        assert_eq!(err.0, ErrorCode::InvalidParams);
        assert!(err.1.contains("exceeds cap"), "error names the cap: {}", err.1);
        kill_all_sessions(&state);
    }

    #[test]
    fn send_input_at_cap_boundary_is_accepted() {
        // 64 KiB exact must be allowed (cap is "no more than" not
        // "less than"). Regression guard against off-by-one.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-si-cap", &dir);
        let uid = spawn_bash(&state, "ws-si-cap");

        // Use a payload that won't make bash do anything dramatic
        // when it parses — a comment with padding. Cap-sized
        // exactly.
        let mut text = String::with_capacity(MAX_SEND_INPUT_BYTES);
        text.push('#');
        while text.len() < MAX_SEND_INPUT_BYTES {
            text.push('x');
        }
        assert_eq!(text.len(), MAX_SEND_INPUT_BYTES);

        let params = json!({ "session_uid": &uid, "text": text });
        let result = send_input(&state, &params).expect("at-cap must succeed");
        assert_eq!(result["ok"], true);
        kill_all_sessions(&state);
    }

    #[test]
    fn send_input_rejects_submit_false_with_parity_message() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-si-sub", &dir);
        let uid = spawn_bash(&state, "ws-si-sub");

        let params = json!({
            "session_uid": &uid,
            "text": "no-submit",
            "submit": false,
        });
        let err = send_input(&state, &params).expect_err("submit=false rejected");
        assert_eq!(err.0, ErrorCode::InvalidParams);
        assert!(err.1.contains("submit=false"), "message must name the field");
        kill_all_sessions(&state);
    }

    #[test]
    fn send_input_unknown_uid_returns_not_found() {
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({
            "session_uid": "ts-ghost",
            "text": "anything",
        });
        let err = send_input(&state, &params).expect_err("unknown uid");
        assert_eq!(err.0, ErrorCode::NotFound);
        assert!(err.1.contains("ts-ghost"));
    }

    // ===========================================================
    // kill_session (slice 10c-d)
    // ===========================================================

    #[test]
    fn kill_session_removes_from_registry_and_terminates_child() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-kill", &dir);
        let uid = spawn_bash(&state, "ws-kill");
        assert!(state.lock().unwrap().sessions.contains_key(&uid));

        let params = json!({ "session_uid": &uid });
        let result = kill_session(&state, &params).expect("kill ok");
        assert_eq!(result["ok"], true);
        assert!(
            !state.lock().unwrap().sessions.contains_key(&uid),
            "kill_session must remove the entry from the registry",
        );
        // The Drop-driven kill via pidfd sent SIGKILL; the reaper
        // observes the exit and the on_exit callback's remove is a
        // no-op (already removed). Nothing to verify beyond the
        // registry being empty.
    }

    #[test]
    fn kill_session_unknown_uid_returns_not_found() {
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({ "session_uid": "ts-never-existed" });
        let err = kill_session(&state, &params).expect_err("unknown uid");
        assert_eq!(err.0, ErrorCode::NotFound);
    }

    // ===========================================================
    // read_session_output (slice 10c-d)
    // ===========================================================

    #[test]
    fn read_session_output_first_call_returns_full_ring() {
        // Spawn bash, send a marker, snapshot the fanout from the
        // start. First call with `since_cursor = None` returns the
        // full ring.
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-rso", &dir);
        let uid = spawn_bash(&state, "ws-rso");

        // Drive some output and wait briefly for it to land in the
        // fanout.
        let _ = send_input(
            &state,
            &json!({ "session_uid": &uid, "text": "echo marker-first-snap" }),
        )
        .expect("send_input");

        // Poll until snapshot.bytes contains the marker — bounded
        // window. The fanout receives bytes asynchronously through
        // the reader thread.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        loop {
            let params = json!({ "session_uid": &uid });
            let result =
                read_session_output(&state, &params).expect("rso ok");
            let b64 = result["bytes"].as_str().unwrap();
            let bytes = BASE64.decode(b64).unwrap();
            if String::from_utf8_lossy(&bytes).contains("marker-first-snap") {
                assert_eq!(result["start_offset"], 0);
                assert!(result["cursor"].as_u64().unwrap() > 0);
                assert_eq!(result["evicted_since_cursor"], false);
                assert_eq!(result["closed"], false);
                kill_all_sessions(&state);
                return;
            }
            if std::time::Instant::now() >= deadline {
                kill_all_sessions(&state);
                panic!(
                    "marker-first-snap not in fanout after 3s; last bytes:\n{}",
                    String::from_utf8_lossy(&bytes)
                );
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
    }

    #[test]
    fn read_session_output_with_cursor_returns_only_new_bytes() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-rso-2", &dir);
        let uid = spawn_bash(&state, "ws-rso-2");

        // First marker.
        let _ = send_input(
            &state,
            &json!({ "session_uid": &uid, "text": "echo CURSOR-A" }),
        )
        .unwrap();
        // Wait for first marker to land.
        let cursor_after_a = wait_for_marker(&state, &uid, "CURSOR-A");

        // Second marker, then snapshot since the first cursor.
        let _ = send_input(
            &state,
            &json!({ "session_uid": &uid, "text": "echo CURSOR-B-marker" }),
        )
        .unwrap();
        // Poll: read_session_output(since=cursor_after_a) must
        // contain CURSOR-B-marker but NOT CURSOR-A.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        loop {
            let params = json!({
                "session_uid": &uid,
                "since_cursor": cursor_after_a,
            });
            let result =
                read_session_output(&state, &params).expect("rso ok");
            let b64 = result["bytes"].as_str().unwrap();
            let bytes = BASE64.decode(b64).unwrap();
            let text = String::from_utf8_lossy(&bytes).to_string();
            if text.contains("CURSOR-B-marker") {
                assert!(
                    !text.contains("CURSOR-A"),
                    "since-cursor must exclude CURSOR-A from before; got:\n{}",
                    text
                );
                assert_eq!(result["start_offset"], cursor_after_a);
                kill_all_sessions(&state);
                return;
            }
            if std::time::Instant::now() >= deadline {
                kill_all_sessions(&state);
                panic!(
                    "CURSOR-B-marker not after cursor {} within 3s; got:\n{}",
                    cursor_after_a, text
                );
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
    }

    #[test]
    fn read_session_output_after_kill_reports_closed_true() {
        let dir = TempDir::new().unwrap();
        let state = state_with_workspace("ws-rso-closed", &dir);
        let uid = spawn_bash(&state, "ws-rso-closed");
        // Kill it (Drop sends SIGKILL via pidfd; reader thread
        // sees EOF, fanout.close() fires).
        // But: kill_session REMOVES the session from the registry,
        // so a follow-up read_session_output would get NotFound,
        // not closed=true. So we test the closed signal via the
        // pre-removal window: send_input then directly close the
        // fanout to simulate child exit while session is still in
        // the registry.
        {
            let mut s = state.lock().unwrap();
            let session = s.sessions.get_mut(&uid).unwrap();
            session.fanout.close();
        }
        let params = json!({ "session_uid": &uid });
        let result =
            read_session_output(&state, &params).expect("rso ok");
        assert_eq!(
            result["closed"], true,
            "closed flag must propagate from FanoutSnapshot",
        );
        kill_all_sessions(&state);
    }

    #[test]
    fn read_session_output_unknown_uid_returns_not_found() {
        let state = Arc::new(Mutex::new(DaemonState::new()));
        let params = json!({ "session_uid": "ts-ghost" });
        let err = read_session_output(&state, &params).expect_err("unknown uid");
        assert_eq!(err.0, ErrorCode::NotFound);
    }

    /// Test helper: drive `read_session_output` polls until the
    /// marker substring appears in the decoded bytes, then return
    /// the cursor at that snapshot. Caps at 3s; panics on timeout.
    fn wait_for_marker(state: &Arc<Mutex<DaemonState>>, uid: &str, marker: &str) -> u64 {
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        loop {
            let params = json!({ "session_uid": uid });
            let result =
                read_session_output(state, &params).expect("rso ok");
            let b64 = result["bytes"].as_str().unwrap();
            let bytes = BASE64.decode(b64).unwrap();
            if String::from_utf8_lossy(&bytes).contains(marker) {
                return result["cursor"].as_u64().unwrap();
            }
            if std::time::Instant::now() >= deadline {
                panic!(
                    "marker '{}' not in fanout within 3s; got:\n{}",
                    marker,
                    String::from_utf8_lossy(&bytes)
                );
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
    }
}
